UNIVERSITY OF DODOMA, COLLEGE OF INFORMATICS AND VIRTUAL EDUCATION

MATHEMATICS FOR DATASCIENCE AND MACHINE LEARNING WITH NUMPY


# NUMPY

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

1)A powerful N-dimensional array object

2)Sophisticated (broadcasting) functions

3)Tools for integrating C/C++ and Fortran code

4)Useful linear algebra, Fourier transform, and random number capabilities
 

 Scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

# Installing packages

Numpy packages is available in different distribution on different key packages  such as the following 

a)Anaconda, it is  free distribution of Python with scientific packages. Supports Linux, Windows and Mac.
when donload the anaconda this come with many package such numpy, panda and other package.

b) Python(x,y) ,this is free distribution including scientific packages, based around the Spyder IDE. Windows and Ubuntu; Py2 only

c) Winpython,  Another free distribution including scientific packages and the Spyder IDE. Windows only, but more actively maintained and supports the latest Python 3 versions.


 Insatall vi pip  ,
 for the window user when want to insatll this package use a commqnd
 python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
 
 for linux and ubunt user use this command , 
 sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
 
 for mac user  use this command  ,
 sudo port install py35-numpy py35-scipy py35-matplotlib py35-ipython +notebook py35-pandas py35-sympy py35-nose

# The baisc

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

for more understand cheki this site of numpy https://docs.scipy.org/doc/numpy/user/quickstart.html

[[1,3,4]]this array has one axe and 3 element,[[2,3,5],[2,3,5]] this array has two axe and 6 element


Before want to use numpy first must be import 

In [37]:
import numpy as np

In [2]:
x=np.arange(15).reshape(3,5)

In [4]:
x.ndim

2

In [5]:
#shape of an array 
x.shape

(3, 5)

In [17]:
#size of element
x.size
#data type of tha array
x.dtype.name

NameError: name 'x' is not defined

# Array creation

In [6]:
y=np.array([3,4,5,6])

In [8]:
y

array([3, 4, 5, 6])

In [9]:
#shape of an array
y.shape

(4,)

In [10]:
#check the size of array
y.size

4

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [16]:
np.arange(20,50,5)

array([20, 25, 30, 35, 40, 45])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step

In [18]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# print array

on c++ we use the keyword cout to give out the information,in python we use the word print with a blacket print()


In [22]:
a=np.arange(3,4)

In [23]:
print(a)

[3]


In [24]:
b=np.array([2,3,4])

In [25]:
print(b)

[2 3 4]


# Trigonometric and round number

In [26]:
number=np.sin(45)

In [27]:
print(number)

0.8509035245341184


In [28]:
number=np.cos(45)

In [29]:
print(number)

0.5253219888177297


In [31]:
# numpy it can use to round anumber nearest munber  by used a function around()
a=np.around([2.36,6.79])

In [32]:
a

array([2., 7.])

In [33]:
# if want to round nearest integer you can use a function calle rint()
num=np.array([2.7,6.4,0.2,66.7])

In [35]:
print(np.rint(num))

[ 3.  6.  0. 67.]


# Sum  and product

In [7]:
number=np.prod([3,5])

In [38]:
print(number)

15


In [7]:
number=np.linspace(2,4,10)

In [8]:
print(number)

[2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
 3.33333333 3.55555556 3.77777778 4.        ]


In [9]:
#to find the sum 
number.sum()

30.0

# Basic operation

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. you can use this package for different opreation such as addition,sub,multiplication 

In [10]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

 

In [11]:
print(b)

[0 1 2 3]


In [13]:
c=a-b
print(c)

[20 29 38 47]


In [14]:
c=a+b
print(c)

[20 31 42 53]


some time you can use the sum,max,min to find the maximun number and minimum number of the given array
See also
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

In [15]:
max(c)

53

In [16]:
min(c)

20

# Indexing and Slicing 

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [22]:
h=np.arange(10)**3

In [23]:
print(h)

[  0   1   8  27  64 125 216 343 512 729]


In [24]:
#index of zero
h[0]

0

In [25]:
#index of 2 is equal to number 4
h[2]

8

In [26]:
h[3:6]

array([ 27,  64, 125], dtype=int32)

# Shape Manipulatiion

An array has a shape given by the number of elements along each axis.you can change the shape of an array according to the needed

In [28]:
b=np.floor(10*np.random.random((3,4)))

In [29]:
b

array([[8., 3., 9., 6.],
       [6., 5., 5., 0.],
       [3., 3., 6., 9.]])

In [30]:
b.ravel()  # returns the array, flattened

array([8., 3., 9., 6., 6., 5., 5., 0., 3., 3., 6., 9.])

In [32]:
#shape the array into 5 rows and 2column
b.reshape(6,2)

array([[8., 3.],
       [9., 6.],
       [6., 5.],
       [5., 0.],
       [3., 3.],
       [6., 9.]])

In [33]:
b.reshape(4,3)

array([[8., 3., 9.],
       [6., 6., 5.],
       [5., 0., 3.],
       [3., 6., 9.]])

In [34]:
b.T  # returns the array, transposed

array([[8., 6., 3.],
       [3., 5., 3.],
       [9., 5., 6.],
       [6., 0., 9.]])

In [35]:
#And also you cna use resize insted of reshape but when use the resise it return 
b.resize((2,6))

In [36]:
b

array([[8., 3., 9., 6., 6., 5.],
       [5., 0., 3., 3., 6., 9.]])

# Stacking together different arrays

In [38]:
 a = np.floor(10*np.random.random((2,2)))

b = np.floor(10*np.random.random((2,2)))


In [39]:
a

array([[5., 6.],
       [5., 7.]])

In [40]:
b

array([[9., 2.],
       [4., 0.]])

In [41]:
np.hstack((a,b))

array([[5., 6., 9., 2.],
       [5., 7., 4., 0.]])

In [42]:
np.vstack((a,b))

array([[5., 6.],
       [5., 7.],
       [9., 2.],
       [4., 0.]])

On the other hand, the function row_stack is equivalent to vstack for any input arrays. In general, for arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.



References

http://localhost:8888/notebooks/Documents/mathematics%20for_ds_and_ml/Untitled.ipynb
    

PREPARED BY MR MANENO 
halidiselemani94@gmail.com